version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: github.com/deanishe/awgo
    versions:
    - 0.27.1
