name: Release new version

on:
  push:
    branches:
      - "main"
    paths:
      - "version"

jobs:
  release:
    if: github.repository == 'AndreyBozhko/go-ghpr'
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Fetch dependencies
        run: |
          go get -v ./...
      
      - name: Compile
        run: |
          for arch in amd64 arm64 ; do
            GOARCH=$arch go build -ldflags "-s -w" -o go-ghpr-$arch workflow.go utils.go
          done
      
      - name: Package
        env:
          alfred_version: 4
          alfred_preferences: ./tools/prefs.json
        run: |
          mkdir build && mkdir dist
          cp LICENSE README.md icon.png info.plist version build/

          for arch in amd64 arm64 ; do
            export alfred_workflow_version=v$(cat version)-$arch
            cp go-ghpr-$arch build/go-ghpr
            go run tools/package.go build dist
          done
      
      - name: Push new tag
        id: tags
        run: |
          TAG=v$(cat version)
          git tag $TAG
          git push origin $TAG
          echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.alfredworkflow
          tag_name: ${{ steps.tags.outputs.latest_tag }}
