name: Release new version

on:
  push:
    branches:
      - "main"
    paths:
      - "version"

jobs:
  release:
    if: github.repository == 'AndreyBozhko/go-ghpr'
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Fetch dependencies
        run: |
          go get -v ./...
      
      - name: Compile
        run: |
          go build -ldflags "-s -w" -o go-ghpr workflow.go utils.go
      
      - name: Package
        env:
          alfred_version: 4
          alfred_preferences: ./tools/prefs.json
        run: |
          export alfred_workflow_version=v$(cat version)
          mkdir build && mkdir dist
          cp LICENSE README.md go-ghpr icon.png info.plist version build/
          go run tools/package.go build dist
      
      - name: Push new tag
        run: |
          TAG=v$(cat version)
          git tag $TAG
          git push origin $TAG

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.alfredworkflow
