name: Release new version

on:
  push:
    branches: [ main ]
    paths: [ version ]

jobs:
  release:
    if: github.repository == 'AndreyBozhko/go-alfred-prs'
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Compile
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o go-ghpr *.go
      
      - name: Package
        env:
          alfred_version: 4
          alfred_preferences: ./tools/prefs.json
        run: |
          touch tools/prefs.json
          mkdir build && mkdir dist
          cp LICENSE README.md go-ghpr icon.png info.plist version build/
          go run tools/package.go build dist
      
      - name: Push new tag
        id: tags
        run: |
          TAG=v$(cat version)
          git tag $TAG
          git push origin $TAG
          echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.alfredworkflow
          tag_name: ${{ steps.tags.outputs.latest_tag }}
