name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: github.repository_owner == 'AndreyBozhko'
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Run tests
        env:
          alfred_workflow_bundleid: me.abozhko.go-ghpr
          alfred_workflow_cache: ./.tmp/cache
          alfred_workflow_data: ./.tmp/data
          alfred_workflow_name: go-ghpr
          alfred_workflow_version: "0.0.1"
        run: |
          go test -v ./...
